name: congle
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # connectivity_plus: ^5.0.0
  connectivity_plus: ^2.2.0
  dotted_border: ^2.1.0
  firebase_analytics: ^10.5.1
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9
  flutter:
    sdk: flutter
  flutter_pin_code_fields: ^2.2.0
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^2.0.5
  fluttertoast: ^8.0.8
  geolocator: ^10.1.0
  get: ^4.6.1
  google_fonts: ^4.0.4
  hexagon: ^0.2.0
  image: ^4.1.3
  image_picker: ^1.0.4
  intl: ^0.18.1
  just_audio: ^0.9.18
  location: ^5.0.3
  multi_image_picker: ^4.8.01
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  scroll_date_picker: ^3.7.3
  syncfusion_flutter_sliders: ^23.1.40
  url_launcher: ^6.0.18
  # videosdk: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
#   flutter_launcher_icons: "^0.9.2"
# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   remove_alpha_ios: true
#   image_path: "assets/icons/logo_wh.png"
# flutter_native_splash:
#   color: "#2871FF"
#   image: assets/icons/logo_wh.png
flutter:
  uses-material-design: true

  assets:
    - assets/icons/main/
    - assets/icons/sec/
    - assets/icons/categories/
    - assets/icons/
    - assets/images/
    - assets/images/onboard/
    - assets/images/step1/
    - assets/images/gender/
    - assets/gifs/
    - assets/audio/date.ogg

  fonts: 
    - family: Hanken Grotesk
      fonts:
        - asset: assets/fonts/HankenGrotesk-VariableFont_wght.ttf
        - asset: assets/fonts/HankenGrotesk-Italic-VariableFont_wght.ttf
          weight: 700

    - family: TestDomaine
      fonts:
        - asset: assets/fonts/TestDomaineDisplayCondensed-SemiboldItalic.otf
          style: italic
          weight: 600
        - asset: assets/fonts/TestDomaineDisplayNarrow-SemiboldItalic.otf
          style: italic
          weight: 600
        - asset: assets/fonts/TestDomaineDisplay-SemiboldItalic.otf
          style: italic
          weight: 600
        - asset: assets/fonts/TestDomaineText-MediumItalic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/TestDomaineText-RegularItalic.otf
          style: italic
          weight: 400


